debug: false
logging:
  file: application.log
server:
  servlet:
    context-path: /myapp
  port: 8090
spring:
  jpa:
    show-sql: true

      
---
spring:
  profiles: dev
  datasource:
    url: 
    username: 
    password: 
debug: false
server:
  port: 8089
    
---
spring:
  profiles: test
debug: false
server:
  port: 8091
---
spring:
  profiles: prod
debug: false
server:
  port: 8091